name: Build and Publish JAR + Image

on:
  push:

jobs:
  define-version:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.get-version.outputs.image_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get feature version
        id: get-version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "image_version=${COMMIT_HASH}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "Image version: ${COMMIT_HASH}-SNAPSHOT"

  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Set up environment variables
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: echo "CAAB_SERVICE_TOKEN=${REPO_TOKEN}" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: upload jarfile
        uses: actions/upload-artifact@v4
        with:
          name: ccms-access-service-adaptor-jar
          path: target/assess-service-adapter.jar

  ecr:
    needs: [ build, define-version ]
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write # for requesting jwt
      contents: read  # for actions/checkout
    steps:
      # Checkout github repo
      - name: checkout repo
        uses: actions/checkout@v4
      - name: download jar
        uses: actions/download-artifact@v4
        with:
          name: ccms-access-service-adaptor-jar
          path: target/assess-service-adapter.jar
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      # Login to container repo
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      # Build and push docker image to container repo
      - name: docker build and push
        run: |
          docker build -t $REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }} .
          docker push $REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }}
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.define-version.outputs.image_version) }}
      - name: delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ccms-access-service-adaptor-jar
