name: Build and Publish JAR + Image

on:
  push:

jobs:
  define-version:
    runs-on: ubuntu-latest
    outputs:
      image_version: ${{ steps.get-version.outputs.image_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get feature version
        id: get-version
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          echo "image_version=${COMMIT_HASH}-SNAPSHOT" >> $GITHUB_OUTPUT
          echo "Image version: ${COMMIT_HASH}-SNAPSHOT"

  build:
    runs-on: ubuntu-latest
    container:
      image: cimg/openjdk:8.0-browsers
    steps:
      - uses: actions/checkout@v4

      - name: Make Maven Wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven wrapper and aws profile
        run: ./mvnw clean install -P aws

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: ccms-assess-service-adapter-jar
          path: target/assess-service-adapter.jar

  ecr:
    needs: [ build, define-version ]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # for requesting jwt
      contents: read  # for actions/checkout
    steps:
      # Checkout github repo
      - name: checkout repo
        uses: actions/checkout@v4
      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: ccms-assess-service-adapter-jar
          path: target/

      - name: Verify JAR
        run: file target/assess-service-adapter.jar

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      # Login to container repo
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
      - name: Build image
        id: build-image
        run: |
          image_name=$REGISTRY/$REPOSITORY:${{ env.IMAGE_TAG }}
          docker build -t $image_name .
          echo "image_name=$image_name" >> $GITHUB_OUTPUT
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ format('{0}-{1}', vars.IMAGE_PREFIX, needs.define-version.outputs.image_version) }}
      - name: Scan image
        if: ${{ inputs.scan_image == 'true' }}
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: ${{ steps.build-image.outputs.image_name }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      - name: Push image
        run: |
          docker push ${{ steps.build-image.outputs.image_name }}
      - name: delete artifact
        uses: geekyeggo/delete-artifact@v5
        with:
          name: ccms-access-service-adapter-jar
