name: Build main

on:
  pull_request:
    branches: [ main, main-cp ]
    types: [ closed ]

jobs:
  build-and-publish-release:
    if: ${{ github.event.pull_request.merged == true }}
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@v1
    permissions:
      contents: write
      packages: write
    with:
      java_version: '8'
      create_tag: 'true'
      override_tagged_branch: 'main-cp'
      github_bot_username: 'laa-ccms-caab-service'
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      github_app_id: ${{ vars.LAA_CCMS_CAAB_SERVICE_APP_ID }}
      github_app_private_key: ${{ secrets.LAA_CCMS_CAAB_SERVICE_KEY }}
      github_app_organisation: 'ministryofjustice'
